# Generated by Django 4.2.5 on 2024-01-11 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="DayOfWeekChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Sunday", "Sunday"),
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("goal", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Week",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("week_number", models.PositiveIntegerField()),
            ],
            options={
                "unique_together": {("year", "week_number")},
            },
        ),
        migrations.CreateModel(
            name="HabitSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("not_completed", "Not Completed"),
                        ],
                        default="not_completed",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("time_spent", models.DurationField(blank=True, null=True)),
                (
                    "day",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="habit_tracker.day"),
                ),
                (
                    "habit",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="habit_tracker.habit"),
                ),
            ],
            options={
                "unique_together": {("habit", "day")},
            },
        ),
        migrations.CreateModel(
            name="HabitRecurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                (
                    "days_of_week",
                    models.ManyToManyField(
                        related_name="habit_recurrences", to="habit_tracker.dayofweekchoice"
                    ),
                ),
                (
                    "habit",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="habit_tracker.habit"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="day",
            name="habits",
            field=models.ManyToManyField(
                related_name="scheduled_habits",
                through="habit_tracker.HabitSchedule",
                to="habit_tracker.habit",
            ),
        ),
        migrations.AddField(
            model_name="day",
            name="week",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="habit_tracker.week"),
        ),
    ]
