# Generated by Django 4.2.5 on 2024-01-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="habitschedule",
            name="time_spent",
            field=models.DurationField(blank=True, default=0, null=True),
        ),
    ]
