# Generated by Django 4.2.5 on 2024-01-17 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("habit_tracker", "0002_alter_habitschedule_time_spent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dayofweekchoice",
            name="day_of_week",
            field=models.CharField(
                choices=[
                    ("Sunday", "Sunday"),
                    ("Monday", "Monday"),
                    ("Tuesday", "Tuesday"),
                    ("Wednesday", "Wednesday"),
                    ("Thursday", "Thursday"),
                    ("Friday", "Friday"),
                    ("Saturday", "Saturday"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="habitschedule",
            name="time_spent",
            field=models.DurationField(blank=True, default=datetime.timedelta(0), null=True),
        ),
    ]
